name: okane
description: "Interactive coach to help you manage your finances efficiently and clearly."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.7.0

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  text_responsive: ^1.2.1
  jocaaguraarchetype: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/google-fonts/