name: okane
description: "Interactive coach to help you manage your finances efficiently and clearly."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.9+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  jocaagura_domain:
    git:
      url: https://github.com/jocaagura/jocaagura_domain
      ref: master
  jocaaguraarchetype:
    git:
      url: https://github.com/jocaagura/jocaaguraarchetype
      ref: master
  text_responsive: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/